### PR TITLE
Avoid leak of friend public keys in export format

### PR DESCRIPTION
**Pull request by sudden6**
ping @naxuroqa @robinlinden @iphy @JFreegman

EDIT: Note that qTox does something similar since a long time, but during a recent discussion with @naxuroqa we came to the conclusion this should be standardized.

### CODE REVIEW

**Comment by naxuroqa** [comment]
:+1: Definitely an improvement to the current standard.

**Comment by sudden6** [comment]
After some discussion with @naxuroqa this is not a good idea anymore. I'll close this and rethink it.

**Comment by JFreegman** [comment]
@sudden6 Can you give us the reason why it's not a good idea so that we can reference this issue in the future if it ever comes up again?

**Comment by sudden6** [comment]
It doesn't really protect anything if someone has the PK of that friend the avatar belongs to. And PKs are easy to get and you can quickly do the hash operation.

The other ideas were to use our own private key with a HMAC. e.g. `HMAC(privKey, PK)` or just encrypt it with our own private key.

**Pull request closed without merging**
