### PR TITLE
Message persistence should be enabled by default

### PR DESCRIPTION
**Pull request by subliun**

### CODE REVIEW

**Comment by JFreegman** [comment]
Logging should be opt-in, not opt-out. This is a security concern.

**Comment by Zer0-One** [comment]
I agree with @JFreegman , logging should be opt-in for security.

**Comment by subliun** [comment]
No sane client (excluding 1337 h4x0r CLI clients (which may or may not qualify as sane; a debate for another time)) is going to have logging disabled by default. It is enabled in literally every popular IM by default, so forcing users to opt-in to this basic feature would be terribly unintuitive and poor UX.

**Comment by JFreegman** [comment]
Our goal is not to copy bad practices of other popular clients, which care little about security. You could make it opt-in once when you create a new profile, or opt-in every time you start a conversation with a new friend. It doesn't matter, as long as logs aren't being stored (possibly in plaintext) on a user's device without their explicit consent.

Also, I may be remembering incorrectly, but wasn't it opt-in for MSN/Windows Live?

**Comment by subliun** [comment]
meh
_tosses TCS on pile of Tox standards Antox will not be following_

**Comment by JFreegman** [comment]
You're obviously not forced to comply, but there will be strong incentives.

**Comment by Zer0-One** [comment]
@JFreegman Another option might be to require that if logging is enabled by default, logs are encrypted. Thoughts?

**Comment by JFreegman** [comment]
Yeah, that's something we could consider

**Comment by JFreegman** [comment]
This change is being rejected on grounds that it's insecure/irresponsible, but I've proposed a couple related changes: https://github.com/Tox/Tox-Client-Standard/pull/14

**Pull request closed without merging**
