### PR TITLE
[Data Storage] - very small style fix

### PR DESCRIPTION
**Pull request by Zer0-One**
Votes to merge (need a majority):
- [x] @Zer0-One 
- [x] @stal888  
- [x] @JFreegman 
- [ ] @JX7P (no vote)
- [ ] @tux3 (no vote)
- [ ] @iphydf (no vote)
- [x] @Impyy

### CODE REVIEW

**Comment by stal888** [comment]
Eh, it's ok.

**Comment by Chuongv** [comment]
I think it was fine as is before.. in my opinion... so I'll abstain my vote.

**Comment by JFreegman** [comment]
Yes, but why is export capitalized?

**Comment by Zer0-One** [comment]
@JFreegman because it's a specific export format that we refer to multiple times, and we didn't give it a name.

**Comment by GrayHatter** [comment]
abs

**Comment by subliun** [comment]
I don't like the commas and I don't like all the 'in's, but it's alright.
:+1:

**Comment by subliun** [comment]
:+1: (you have majority, merge)

**Comment by alexbakker** [comment]
Looks fine. :+1:

**Comment by netbsduser** [comment]
I would use $XDG_CONFIG_DIR/tox as the standard location on Unix-likes, falling back to ~/.config/tox only when this variable is unset. This would align with the recommendations of the X11 Desktop Group.

**Comment by GrayHatter** [comment]
what about toxic without X11?

Honestly it should be $HOME/.config/tox

https://en.wikipedia.org/wiki/Home_directory

**Comment by netbsduser** [comment]
@GrayHatter 

> falling back to ~/.config/tox only when this variable is unset

**Comment by GrayHatter** [comment]
I think ~ is just a common alias for $HOME ash that if  home is unset, ~
will resolve to nothing

**Pull request merged**
