### PR TITLE
Add section about Identicon algorithm

### PR DESCRIPTION
**Pull request by sudden6**

### CODE REVIEW

**Comment by sudden6** [comment]
I think we should move the spec document into this repo if it gets accepted, consider the current formatting a draft.

**Comment by tox-user** [comment]
Looks good but you should add the linked document to the commit so that we get it in this repo. I assume you have read that document and it's correct?

**Comment by sudden6** [comment]
I have read the document and verified it's correct.

@robinlinden @naxuroqa added specification inside the repository as requested.

**Comment by naxuroqa** [comment]
I implemented the algorithm according to this document in vala and can confirm that the output is identical to the qtox identicons.

**Pull request merged**
